### ISSUE TITLE
Xenos and Logic Pro error

### ISSUE THREAD

**Issue by kreisbed** [raphaelradna/xenos#3]
I installed version 1.0 for the Mac. I got this error message when booting Logic Pro : 

Xenos.component” can’t be opened because Apple cannot check it for malicious software.

I tried enabling it in the Plug-in Manager, but it still doesn't show up as an instrument. Any suggestions?

**Comment by raphaelradna** [comment]
This seems to be a function of the Apple "Gatekeeper."
I'd try removing the quarantine attribute from the plug-in bundle.
Here's how to do that:
1. Open the Terminal app
2. Paste in the following command (without the quotation marks but making sure to keep the space at the end)
> "xattr -dr com.apple.quarantine "
3. Drag Xenos.component onto the Terminal window
4. Press return
5. Give it another shot!

**Comment by kreisbed** [comment]
Thanks for the quick response - your suggestion worked perfectly.  I'm sure this will provide hours of fun exploring all the sound options.

**Comment by raphaelradna** [comment]
Great—glad to hear it!
