### ISSUE TITLE
Possible global memory error - multiple instances of different plugin formats causes crashes

### ISSUE THREAD

**Issue by tank-trax** [raphaelradna/xenos#5]
I have successfully built Xenos on Debian 11 and Mint 20.3 using JUCE 7.0.5 for VST2, VST3, LV2 and Standalone. It runs perfectly BTW.

However, I noticed an issue when loading or unloading multiple instances of Xenos using different plugin formats.

For example, loading/unloading as many instances in a Reaper session, of either LV2, VST2 or VST3 of Xenos is possible. Multiple instances of Xenos VST3 can be added to one track or several unique instances to multiple tracks, they can be added or removed without issue. However if an LV2 or VST2 is attempted to be added to the session the DAW will crash.

As per baconpaul, this could be a global memory error. That when there are two instances of the same global table from the two plugins this causes the crash.

I cannot test this on Windows or OSX to see if this behaviour is isolated to Linux or not.

**Comment by raphaelradna** [comment]
Thanks—I wonder if this is related to #4.
Does the crash only happen when mixing plug-in formats in the same session?
Can you get any info from debugger or crash report?

**Comment by tank-trax** [comment]
it looks to have been an issue isolated to Linux

MXTune had a similar problem with instance crashing and Paul Davis intervened
https://github.com/liuanlin-mx/MXTune/issues/6

I basically added the line
 `-fvisibility=hidden -fdata-sections -ffunction-sections -Wl,--gc-sections -Wl,-O1 -Wl,--as-needed -Wl,--strip-all` 
 
 to Extra Compiler Flags in the Jucer file and the exposed symbols were eliminated when running the command
 
 `objdump -T Xenos.so | grep ' g ' `
 
 as were the plugin crashes 
 
 after these changes, it's possible to add remove as many instances of Xenos in a DAW session and as many formats without crashes

![image](https://user-images.githubusercontent.com/41337033/219268091-36be5abe-bcf5-4e07-a5fa-ec11f5dbdf7c.png)

thanks
