### ISSUE TITLE
LV2 version?

### ISSUE THREAD

**Issue by mxmilkiib** [raphaelradna/xenos#6]
Hi! Wondering if an LV2 version might be possible? Thanks!

**Comment by atsushieno** [comment]
I could build LV2 version using JUCE7 on Mac. If you add Linux build settings to `Xenos.jucer` it would just work as well. (If it was `CMakeLists.txt` then no source changes would be needed.)

**Comment by raphaelradna** [comment]
As of [v1.0.1](https://github.com/raphaelradna/xenos/releases/tag/v1.0.1), Linux binaries (VST3 and LV2) are available for download. The repo has also been updated with instructions for building from source on Linux (thanks @rodneydup!).
